name: Rust

on:
  push:
    tags:
       - '*'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  relase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/release/discord-bot"
        body: "Discord bot release ${{ github.ref }}."
        draft: true
